//HintName: TalariaRegistrations.g.cs
// <auto-generated/>
using Microsoft.Extensions.DependencyInjection;
using Talaria.Core.Registration;
using Talaria.Core;

namespace Talaria.Generated
{
    public static class TalariaHandlerExtensions
    {
        public static TalariaBuilder AddTalariaHandlers(this TalariaBuilder builder)
        {
            builder.Services.AddTransient<global::TestNamespace.MyHandler>();
            return builder;
        }

        public static IServiceProvider MapTalariaHandlers(this IServiceProvider provider)
        {
            provider.MapTopic<global::TestNamespace.MyMessage>("orders.placed", (msg, ct) =>
            {
                var instance = provider.GetRequiredService<global::TestNamespace.MyHandler>();
                return instance.HandleOrder(msg);
            });
            provider.MapTopicWithEnvelope<global::TestNamespace.MyMessage>("inventory.updated", (msg, ct) =>
            {
                var instance = provider.GetRequiredService<global::TestNamespace.MyHandler>();
                instance.HandleSyc(msg, ct);
                return System.Threading.Tasks.Task.CompletedTask;
            });
            return provider;
        }
    }
}
