using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Talaria.SourceGenerators;

[Generator]
public sealed class TalariaIncrementalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Find all methods with [TalariaHandler]
        var handlerDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Talaria.Core.Attributes.TalariaHandlerAttribute",
                predicate: static (s, _) => s is MethodDeclarationSyntax,
                transform: static (ctx, _) => GetHandlerRegistration(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        // 2. Generate the extension method class
        var compilationAndHandlers = context.CompilationProvider.Combine(handlerDeclarations.Collect());
        
        context.RegisterSourceOutput(compilationAndHandlers, static (spc, source) =>
        {
            var (compilation, handlers) = source;
            Execute(spc, compilation, handlers);
        });
    }

    private static HandlerRegistration? GetHandlerRegistration(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not IMethodSymbol methodSymbol)
            return null;

        var classSymbol = methodSymbol.ContainingType;
        if (classSymbol == null)
            return null;

        // Ensure we have exactly one parameter for the message (either T or MessageEnvelope<T>)
        var parameters = methodSymbol.Parameters;
        if (parameters.Length == 0)
            return null; // Invalid signature

        var messageParameter = parameters[0];
        INamedTypeSymbol? messageTypeSymbol = null;
        bool isEnvelope = false;

        if (messageParameter.Type is INamedTypeSymbol namedType && 
            namedType.IsGenericType && 
            namedType.ConstructedFrom.MetadataName == "MessageEnvelope`1")
        {
            messageTypeSymbol = namedType.TypeArguments[0] as INamedTypeSymbol;
            isEnvelope = true;
        }
        else if (messageParameter.Type is INamedTypeSymbol payloadType)
        {
            messageTypeSymbol = payloadType;
            isEnvelope = false;
        }

        if (messageTypeSymbol == null)
            return null;

        // Parse the attribute arguments
        var attr = context.Attributes.FirstOrDefault(a => a.AttributeClass?.Name == "TalariaHandlerAttribute");
        if (attr == null)
            return null;

        string topicName = "";
        if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value != null)
        {
            topicName = attr.ConstructorArguments[0].Value.ToString();
        }
        
        // Optional ConsumerGroup property
        string? consumerGroup = null;
        foreach (var namedArg in attr.NamedArguments)
        {
            if (namedArg.Key == "ConsumerGroup")
            {
                consumerGroup = namedArg.Value.Value?.ToString();
            }
        }

        bool returnsTask = methodSymbol.ReturnType.Name == "Task" || methodSymbol.ReturnType.Name == "ValueTask";

        return new HandlerRegistration
        {
            TopicName = topicName,
            ConsumerGroup = consumerGroup,
            ClassFullName = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            MethodName = methodSymbol.Name,
            MessageFullName = messageTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            IsEnvelope = isEnvelope,
            HasCancellationToken = parameters.Length > 1 && parameters[1].Type.ToDisplayString() == "System.Threading.CancellationToken",
            ReturnsTask = returnsTask
        };
    }

    private static void Execute(SourceProductionContext spc, Compilation compilation, ImmutableArray<HandlerRegistration> handlers)
    {
        if (handlers.IsDefaultOrEmpty)
        {
            spc.AddSource("NoHandlers.g.cs", SourceText.From("// NO HANDLERS FOUND", Encoding.UTF8));
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Talaria.Core.Registration;");
        sb.AppendLine("using Talaria.Core;");
        sb.AppendLine();
        sb.AppendLine("namespace Talaria.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public static class TalariaHandlerExtensions");
        sb.AppendLine("    {");
        
        // 1. AddTalariaHandlers extension for IServicesCollection (registers handler classes)
        sb.AppendLine("        public static TalariaBuilder AddTalariaHandlers(this TalariaBuilder builder)");
        sb.AppendLine("        {");
        
        var distinctClasses = handlers.Select(h => h.ClassFullName).Distinct();
        foreach (var className in distinctClasses)
        {
            sb.AppendLine($"            builder.Services.AddTransient<{className}>();");
        }
        
        sb.AppendLine("            return builder;");
        sb.AppendLine("        }");
        sb.AppendLine();
        
        // 2. MapTalariaHandlers extension for IServiceProvider
        sb.AppendLine("        public static IServiceProvider MapTalariaHandlers(this IServiceProvider provider)");
        sb.AppendLine("        {");
        
        foreach (var handler in handlers)
        {
            string topicArg = $"\"{handler.TopicName}\"";
            string mapMethod = handler.IsEnvelope ? "MapTopicWithEnvelope" : "MapTopic";
            
            // Generate the delegate that resolves the class from DI and invokes the method
            sb.AppendLine($"            provider.{mapMethod}<{handler.MessageFullName}>({topicArg}, (msg, ct) =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                var instance = provider.GetRequiredService<{handler.ClassFullName}>();");
            
            string callArgs = handler.HasCancellationToken ? "msg, ct" : "msg";
            
            if (handler.ReturnsTask)
            {
                sb.AppendLine($"                return instance.{handler.MethodName}({callArgs});");
            }
            else
            {
                sb.AppendLine($"                instance.{handler.MethodName}({callArgs});");
                sb.AppendLine("                return System.Threading.Tasks.Task.CompletedTask;");
            }
            sb.AppendLine("            });");
        }
        
        sb.AppendLine("            return provider;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("TalariaRegistrations.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private record HandlerRegistration
    {
        public required string TopicName { get; init; }
        public string? ConsumerGroup { get; init; }
        public required string ClassFullName { get; init; }
        public required string MethodName { get; init; }
        public required string MessageFullName { get; init; }
        public required bool IsEnvelope { get; init; }
        public required bool HasCancellationToken { get; init; }
        public required bool ReturnsTask { get; init; }
    }
}
